FILE(GLOB sources src/*.c)
add_library(VDB30 ${sources})
target_include_directories(VDB30 PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)

install(
  TARGETS VDB30
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}/ghaas
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/ghaas
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}/ghaas
)
install(
  FILES
    ${CMAKE_CURRENT_SOURCE_DIR}/include/vdb.h
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ghaas
)
